CREATE TABLE STUDENT(
STUID INT,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(50),
CITY VARCHAR(25),
ADDRESS VARCHAR(100)
)

INSERT INTO STUDENT VALUES(1011,'Keyur','Patel','techonthenet.com','Rajkot','A-303 ‘Vasant Kunj’, Rajkot'),
(1022, 'Hardik','Shah', 'digminecraft.com','Ahmedabad',' “Ram Krupa”, Raiya Road'),
(1033, 'Kajal','Trivedi', 'bigactivities.com','Baroda', 'Raj bhavan plot, near garden'),
(1044,'Bhoomi','Gajera', 'checkyourmath.com', 'Ahmedabad','“Jig’s Home”, Narol'),
(1055, 'Harmit','Mitel','@me.darshan.com','Rajkot','B-55, Raj Residency'),
(1066, 'Ashok', 'Jani', NULL, 'Baroda',' A502, Club House Building')

SELECT *FROM STUDENT

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'K%'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____'

SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE '_____A'

SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE '%TEL'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'HA%T'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'K_Y%'

SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '%JER%' 

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '[R,B]%'

SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NOT NULL

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '[A-H]%'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE'_[A,E,I,O,U]%'

SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NULL  AND FIRSTNAME LIKE '_____'

SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE '%PAT'

SELECT FIRSTNAME FROM STUDENT WHERE CITY NOT LIKE 'B%'

--PART B

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '[A,H]%'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'H[A,E,I,0,U]%'

SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME  NOT LIKE '%A'

SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME NOT LIKE '[A,E,I,O,U]%'

SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE LIKE '%.NET%'

--PART C

SELECT FIRSTNAME FROM STUDENT WHERE ADDRESS LIKE '%-%'



