 ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),PINCODE INT
 SELECT * FROM DEPOSIT

 ALTER TABLE DEPOSIT ALTER COLUMN CITY VARCHAR(35)
 SELECT * FROM DEPOSIT

 ALTER TABLE DEPOSIT  ALTER COLUMN AMOUNT INT
  SELECT * FROM DEPOSIT

 SP_RENAME 'DEPOSIT.ACTNO' ,'ANO'
 SELECT * FROM DEPOSIT

 ALTER TABLE DEPOSIT DROP COLUMN CITY
 SELECT * FROM DEPOSIT

 SP_RENAME 'DEPOSIT' , 'DEPOSIT_DETAIL'
 SELECT * FROM DEPOSIT_DETAIL

 SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'
 SELECT * FROM DEPOSIT_DETAIL

ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE
SELECT *FROM DEPOSIT_DETAIL

SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME' 

CREATE TABLE STUDENT_DETAIL(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(25),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)

ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT

ALTER TABLE STUDENT_DETAIL ALTER COLUMN NAME VARCHAR(35)

ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT

SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO'

ALTER TABLE STUDENT_DETAIL DROP COLUMN CITY

SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'

CREATE TABLE DEPOSIT_DETAIL(
ANO INT,
CUSTOMERNAME VARCHAR(35),
BNAME VARCHAR(50),
AMOUNT INT,
PINCODE INT
)

SELECT *FROM DEPOSIT_DETAIL

DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT>=4000
DELETE FROM DEPOSIT_DETAIL WHERE BNAME='CHANDI BRANCH'
DELETE FROM DEPOSIT_DETAIL WHERE ANO>105

TRUNCATE TABLE DEPOSIT_DETAIL

DROP TABLE DEPOSIT_DETAIL

CREATE TABLE EMPLOYEE_MASTER(
EMPNO INT,
EMPNAME VARCHAR(25),
JOININGDATE DATETIME,
SALARY DECIMAL(8,2),
CITY VARCHAR(20)
)

INSERT INTO EMPLOYEE_MASTER VALUES(101,'Keyur', '2002-01-05', 12000, 'Rajkot'),(102,'Hardik','2004-02-15',14000, 'Ahmedabad'),(103, 'Kajal','2006-03-14', 15000, 'Baroda'),(104, 'Bhoomi','2005-06-23',12500, 'Ahmedabad'),(105,'Harmit','2004-02-15', 14000, 'Rajkot'),(106, 'Mitesh' ,'2001-09-25' ,5000 ,'Jamnagar'),(107,'Meeera',null,7000,'Morbi'),(108,'Kishan','2003-02-06' ,10000, NULL)




